### PR TITLE
Create T2

### PR DESCRIPTION
**Pull request by Diliptk**
Please, leave ur comment

### CODE REVIEW

**Comment by GPTRCS159** [comment]
welcome

**Comment by Abhishekgpt123** [comment]
Hii

**Comment by Poojakpoojak** [comment]
Hlo

**Comment by Manoj1223** [comment]
Hi dilip

**Comment by Keerthanakeertha** [comment]
Hi

**Comment by Gowthams14** [comment]
Hi welcome

**Comment by Apoorvil** [comment]
Hi

**Comment by GPTRCS159** [comment]
hiii

**Comment by PremapremaGM** [comment]
Hello

**Comment by Poojecc** [comment]
Hello

**Comment by Gowthams14** [comment]
Hi deliip

**Comment by Poornachandratejaw** [comment]
Hiiii

**Comment by Shrinivasa123** [comment]
Hi dileep tk How are you

**Pull request closed without merging**
